### ISSUE TITLE
Zoom options

### ISSUE THREAD

**Issue by gucantine** [avdaredevil/highcharts-chart#10]
Hi,

I ve got a problem with x axis zoom. When i set data dynamically in the chart and i clicked on the "All" button, after 2-3 minutes the selection in the zoom time panel decreases step by step. 

Do you have a solution?
Thanks

**Comment by gucantine** [comment]
Anyone?

**Comment by avdaredevil** [comment]
Hey @gucantine, sorry for the late reply. I've been rather swamped lately.

To set dynamic zooming, just bind against the `xZoom` and `yZoom` properties.

> Example
```html
<highcharts-chart data="[[data]]" x-zoom="[[hasXZoom]]" y-zoom="[[hasYZoom]]"></highcharts-chart>
```

**Comment by gucantine** [comment]
Thanks for your answer but as you can see, always same problem
 
![image](https://cloud.githubusercontent.com/assets/15328994/16867085/14f2fa92-4a70-11e6-99b7-dbce2e36d383.png)

The xZoom don't set extremes values..While rangeSelector.selected is set to 3 => "All"

What can i do? Set input date (From and To) dynamically ?

**Comment by avdaredevil** [comment]
Sorry for the delay again.

That is true. Could you send me sample code for how you are currently *imperatively* changing zoom ratios. I will put that as an API in either the `highcharts-behavior` or the `highcharts-stock` depending on how it's used. Sounds good?

**Comment by avdaredevil** [comment]
@gucantine Could you please respond? I'll reopen this issue if I get a message or +1.

**Comment by gucantine** [comment]
Sorry for the delay, i fixed my error thanks @avdaredevil

**Comment by avdaredevil** [comment]
No Problem, thanks for using the library!

PS. Leave a post of your solution, in case another person comes across the same problem.
