### ISSUE TITLE
Chart not rendering in IE11

### ISSUE THREAD

**Issue by jpnkicker14** [avdaredevil/highcharts-chart#12]
Cannot get chart to render in IE11 including the demo site ones https://avdaredevil.github.io/highcharts-chart/

**Comment by avdaredevil** [comment]
Hey @jpnkicker14. According to the [compatibility chart](http://caniuse.com/#feat=imports), IE11 shows **HTML imports** as unsupported (*which is critical for Polymer to work*).

Now you can get that functionality via a [Polyfill](https://github.com/webcomponents/webcomponentsjs), and that should fix it!

If you're using any ie browser below 11, the polyfills will not completely work [marked as `~` on the Polyfill Compatibility chart].

**Comment by avdaredevil** [comment]
After debugging further, I've realized IE is simply not parsing the JS correctly in Strict Mode. However by making it non-standard mode, and ES5'ing (commit 8860c93464c386aebe4c930ce45ad689cd538ec2) the demo page, it loads on IE.

Unfortunately the published library cannot exist without `"use strict";`
So the error in the console:
> `SCRIPT1046: Multiple definitions of a property not allowed in strict mode`
In File [highcharts-behavior.html](https://github.com/avdaredevil/highcharts-chart/blob/master/highcharts-behavior.html#L17-L141)

Needs to be fixed before proper compat is available for use. I cannot see why that error should exist, as I do not re assign a variable twice.

**Comment by avdaredevil** [comment]
So I found it, it was the `_loadingUpdate` key in the main behavior. Thanks for your issue!
The library should be completely working on IE11.

If you like the library, don't forget to leave a star/donate!
