### ISSUE TITLE
Real Time Axis Settings 

### ISSUE THREAD

**Issue by calugo** [avdaredevil/highcharts-chart#16]
Hello, 

Sooo, I am using this very cool component in an application using electron+polymer which reads real time data from a microcontroller, via serial port.

All is good, however I have had some trouble shifting the plotted data as the new data is read. (See pic) 

![screenshot - 250217 - 01 36 13](https://cloud.githubusercontent.com/assets/6739276/23326849/f2f8f572-fafa-11e6-936f-eef3853d98ff.png)

Now, my problem is that I cannot find a way to control the (xmin,xmax) but using reRender(), the documentation in highcharts has an example using a function for the Axis called setExtremes, which I have not been able to find in this component. 

What I do is to fill in an array with data and after a number has been reached push - shift - reRender, but I was wondering if there is some other way of doing so which would allow more binding and customisation on the fly?

This is the markup of the element and the properties:
 ```
<div id="hccontainer">
     <highcharts-chart id="hcplot"
     type="line"
     plot-options=[[plotOptions]]
     title="Sensor A0 time-series"
     x-axis=[[xoptions]]
     y-axis=[[yoptions]]
     ></highcharts-chart>
    </div>
```
The options which are kind of irrelevant:

```
        xoptions:{
          type: Object,
          value:{
            //min: 0,
            maxPadding: 0.05,
            minPadding: 0.05,
            //hendOnTick: false,
            //tickAmount: 10,
            //type: 'datetime',
            //tickPixelInterval: 150,
            //maxZoom: 20 * 1000
          },
          notify:true,
        },

        yoptions:{
          type: Object,
          value:{
            min: -1.0,
            max: 5.5,
            tickAmount: 8,
          },
          notify: true,
        },

        plotOptions:{
          type:Object,
          value:{
                  line: {
                    marker: {
                       enabled: false,
                    }
                 }
               },
        },


```
here is my plot function:

`   
plotdata: function(){

        if ((this.sensor)&&(this.sensor.instance)){
        _this=this
        this.sensor.instance.scale(0,5).on('data', function(){
        if (_this.drawswitch==true){
            _this.tseries.push([_this.pltindex*(_this.freq/1000.0),_this.sensor.instance.value])
            if(_this.pltindex>100){
            _this.tseries.shift()
            }
            if (_this.pltindex%2==0){
            _this.$.hcplot.reRender()
            _this.$.hcplot.setData(_this.tseries)
            }
            _this.pltindex++
          }
        })
       }
      },
`
I would really appreciate any suggestion to have some more control over the real time updates which i would like to be able to manipulate from the gui somehow.

Thanks,

**Comment by avdaredevil** [comment]
Am I correct in assuming you want behavior similar to the [first example on my demo](https://avdaredevil.github.io/highcharts-chart/) [_Click Realtime_]?

In that case, the API provided is 
```javascript
_this.$.hcplot.pushData([_this.pltindex*(_this.freq/1000.0),_this.sensor.instance.value])
```

However you'll want to do `addData` in the beginning till your ChartData grows to the size you'd like, then keep pushing (which will drop the last data point, and add a new one in the end). The extremes are auto-calculated

However **Anytime you want direct access to the _Highcharts API_**, simply use the `_chart` property (which is that element's corresponding _Highcharts Object_). So in your case, that is:

```javascript
_this.$.hcplot._chart.xAxis[0].setExtremes(<foo>,<bar>)
```

**Comment by calugo** [comment]
Hello @avdaredevil ,

Thanks for replying, yes the solution you propose is what I did at the beginning and it sort of works I must say that it is slightly tricky if the axis settings are not well tuned as the plot behaves in funny ways (it gets deformed) until the stream is stopped. 

Thanks for the API solution as well!  All works now, I will put the app in github as soon as I finish it so you can try it if you want. 

Very cool compontent indeed.

Best wishes, 

Carlos.

**Comment by avdaredevil** [comment]
Hi @calugo,

Glad to help! Looking forward to trying out your project!
If you liked the component make sure to leave a star! Thanks
