### ISSUE TITLE
highcharts-chart doesn't render, when included indirectly via another web component

### ISSUE THREAD

**Issue by hadjian** [avdaredevil/highcharts-chart#20]
Hi there,

I am trying out this nice web component and everything worked fine until the highcharts module pulled via bower updated the patch level from 5.0.9 to 5.0.14. 

I put together two examples to show this behavior:
https://github.com/hadjian/highcharts-chart-broken-with-5.0.14
https://github.com/hadjian/highcharts-chart-working-with-5.0.9

The one, that is working explicitly pulls highcharts version 5.0.9 in bower.json. Both projects are based on the polymer starter example and include the highcharts-chart component via src/polytest-app/polytest-app.html. Including the component directly in index.html seems to work in both cases. Apologies in advance, if I made some newcomer mistake.

Regards,

Pedram

**Comment by avdaredevil** [comment]
Hmm. I just tested this. It seems there may be a bug in the _**5.0.14 release**_.

The component only relies on the Constructor: `new Highcharts.Chart(config)` working. Which works w/o an exception. But the chart does not actually render. Looking at the [***Changelog***](https://www.highcharts.com/documentation/changelog#highstock). I don't see anything really popping out at me.

If you have any inkling as to why this might be happening feelfree to update the issue. And I can update the lib. Other options are:

- File an issue on Highcharts regarding the constructor
- Pull request with a fix

Thanks!

**Comment by michelbb** [comment]
Having Highcharts > 5.0.12 won't render the chart component in my app as well.

**Comment by avdaredevil** [comment]
Were you able to get it working w/o the web-component using `new Highcharts.Chart(config)`?

This will help us ascertain whether the issue lies within the component or the new constructor.

**Comment by avdaredevil** [comment]
Should no longer be a problem as of version `3` of this component. Closing :)
