### ISSUE TITLE
Upgrading to Polymer 2.x

### ISSUE THREAD

**Issue by varletconst** [avdaredevil/highcharts-chart#22]
Hi,
Thanks for having created this component !
I am planning to use it in my Polymer 2.x project.
I can initiate an upgrade to polymer 2.x but just wondering if you could create a branch for that (because it is going to be a full Polymer 2.x upgrade not hybrid).
Please let me know what your thoughts are on this.

**Comment by avdaredevil** [comment]
Sure! I've been thinking of doing that as well but wasn't sure about the support for it. I believe yarn is the new target CLI tool to acquire polymer 2.0 packages.

So I'm more than OK with making the branch, but I'd prefer keeping it as in-line with the Polymer 2.0 Best Practices as possible.

Does the branch `polymer-2.0` work?

**Comment by varletconst** [comment]
Sorry for my belated reply.

The `polymer-2.0` branch name works fine.
As for releasing the component to npm ([yarn](https://www.polymer-project.org/blog/2017-08-22-npm-modules.html)), I think it is a bit too early (and I am using bower for my front-end deps for now), but it is definitely something we need to consider...
Let me know once you've created the branch.

Thanks.

**Comment by avdaredevil** [comment]
Here it is: https://github.com/avdaredevil/highcharts-chart/tree/polymer-2.0

Appreciate your interest and excitement in the matter! 💯
