### ISSUE TITLE
Angular?

### ISSUE THREAD

**Issue by malikfaizanhaider** [avdaredevil/highcharts-chart#29]
It's possible to use in angular 4 app?

**Comment by avdaredevil** [comment]
Checking... will let you know!

**Comment by avdaredevil** [comment]
It seems so: https://www.sitepen.com/blog/2017/09/14/using-web-components-with-angular/
Looks outdated, but I believe the support should still exist

**Comment by malikfaizanhaider** [comment]
Sure...
