### ISSUE TITLE
Is it possible to create a gauge element with this library?

### ISSUE THREAD

**Issue by FraLeNuvolee** [avdaredevil/highcharts-chart#30]
I created some charts, very nice element btw, but i'm not able to create a gauge, could you please give me some infos?

**Comment by avdaredevil** [comment]
Yeah, it seems the gauge chart doesn't play to friendly generally with Highstock.js. I don't have enough time to file a bug with Highcharts, but if you can send over a fiddle with the part where you get stuck with the creation of the chart. I can make an issue with @highcharts.

FYI: Use:
```
<link rel="import" href="https://raw-dot-custom-elements.appspot.com/avdaredevil/highcharts-chart/v2.0.1/highcharts-chart/highcharts-chart.html">
```
To import the web-component

**Comment by avdaredevil** [comment]
Closing this issue as part of housekeeping, feel free to add to the bug, if you were able to solve this!
