### ISSUE TITLE
Problems using dom-repeat with highcharts

### ISSUE THREAD

**Issue by xxxfanta** [avdaredevil/highcharts-chart#34]
Hey there,

i've an issue when trying to render highcharts inside a <dom-repeat> // <template is="dom-repeat">.

It doesn't render the chart at all (not to mention that it doesn't get the items inside the data-attribute).

Snippet:
```
<div class="card card--1-5 text-center animated fadeInUp">
    <div class="card__chart">
        <highcharts-chart
                index$="[[index]]"
                id$="[[index]]"
                style="min-height: auto;"
                type='pie'
                tooltip-options='{"enabled":false}'
                color-by-point='true'
                highchart-options='{"chart":{"height":"150px"},"plotOptions":{"pie":{"colors":["#2f84e5","#f5f8fb"],"dataLabels":{"enabled":false},"innerSize":"80%","center":["50%","50%"]}}}'
                chart-options='{"backgroundColor": null}'
                data='[50,50]'
                title=''>
        </highcharts-chart>
    </div>
</div>                                
```

Do you have any idea how to debug this one or fix it?
It works fine when it's not inside another template-tag..

**Comment by avdaredevil** [comment]
Could you please reproduce on a jsfiddle? Thanks :)

**Comment by avdaredevil** [comment]
Could you please reproduce on a jsfiddle? Thanks!

I'm sure it is probably a trivial issue, I've done this use case numerous times in the past

**Comment by avdaredevil** [comment]
I'm going to close this since this might be stale at this point, if you still have this issue, I'm happy to work through it again
