### ISSUE TITLE
Highchart World Cloud?

### ISSUE THREAD

**Issue by Tatachiblob** [avdaredevil/highcharts-chart#35]
Is there a way to render the Highcharts word cloud in Polymer?

**Comment by avdaredevil** [comment]
If Highcharts supports it as a library, you can follow suit like:

    <link rel='import' href='/path/to/highcharts-chart.html'>
    <script src='/path/to/plugin.js'>
    <highcharts-chart type='<whatever_word_cloud_type_is>' other-props='foo'>

If you can include a jsfiddle or example page, I can be of more help!

**Comment by Tatachiblob** [comment]
Hello @avdaredevil , thank you for the reply! Fortunately, I was able to make my own highcharts element in polymer 3 and the wordcloud works well. I still appreciate for your Highcharts wrapper.

**Comment by avdaredevil** [comment]
Glad you got it working, though there is a Polymer 3 wrapper under the polymer-3 branch in this repository!
