### ISSUE TITLE
Install Highcharts locally

### ISSUE THREAD

**Issue by sorin-davidoi** [avdaredevil/highcharts-chart#4]
**Use case**: After doing `bower install`, it is common to expect that everything that is needed to run the application is installed in `bower_components`.

**Behavior**: Highcharts is loaded directly from their website.

**Expected behavior**: Should be installed via `bower`.

How do you feel about this? I could do a pull request if it's alright with you.

**Comment by avdaredevil** [comment]
You're absolutely correct! I had overlooked it in the beginning and I guess I never revisited it again. I've made the fix here: 04bc94f20f88224bdafeef0f544a0468042cfa30. In fact in version `1.1.0` that will come out next week or the week after, It will rely on this to support Highmaps and Highstock.

**Comment by avdaredevil** [comment]
__EDIT:__ I've release it today! You can now use all Three Suites.

- highcharts-chart - Highstock/Chart
- highcharts-map  - Highmaps

Let me know if you have any suggestions or feedback! Thanks
