### ISSUE TITLE
Multiple Series Data

### ISSUE THREAD

**Issue by avn4986** [avdaredevil/highcharts-chart#5]
How to use multiple series data? I tried to use the addSeries function but it wouldn't recognize it. 
Also, what dependencies have to be added if RequireJS is being used?

**Comment by avdaredevil** [comment]
Hi Avneesh,

Could you please include an example of how you are attempting:
- Including the library in your app
- Adding a Series

**Comment by avdaredevil** [comment]
Hey, I'm gonna close this issue. If you still have concerns let me know, and I'll re-open this issue.
