### ISSUE TITLE
ability to set height

### ISSUE THREAD

**Issue by kmulvey** [avdaredevil/highcharts-chart#8]
is there a way to specify the height of a graph? I want to stack four spline charts vertically in the viewport and have them be relatively sized 25%. I'm using iron-flex-layout for the structure but the graphs are overflowing their containers.

**Comment by avdaredevil** [comment]
Could you include a snippet of your code (html, CSS) so I can Better understand your issue.

In terms of styling you can set up your page like so:
```html
<highcharts-chart data="[[yourdata]]" on-chart-load="adjustHeight">
<style>
    highcharts-chart {
        --highcharts-min-height: initial
        height: 100%
    }
</style>
<script>
    // Assuming your app scope is set as "var app = #app"
    app.adjustHeight = e => {
        const chart = e.detail.component
        // This does a reflow to parent (height and width) in contrast to .resizeChart() [which only does a width reflow, but ensures responsiveness on window resize]
        chart.resizeChartFixed()
    }
    // For Optional responsive code:
    window.addEventListener('resize', function(e) {
        $("highcharts-chart").each((_,c) => {c.resizeChartFixed()})
    })
</script>
```

Let me know if that works for you (_haven't tested it_)

**Comment by kmulvey** [comment]
I added that and it doesn't seem to work, the graphs still seem to overflow their containers. here is the code and a running example.  Thanks

https://github.com/kmulvey/weather
https://kmulvey.github.io/weather/

**Comment by avdaredevil** [comment]
OK so you have a few issues the style tag needs to look like
```html
<style is="custom-style">
```
your XAxis property has to be set as `x-axis='{"type":"logarithmic"}'` not `xAxis`

other than that you need the styles on the chart to look like this:
```html
<style is="custom-style">
    highcharts-chart {height: 100%; --highcharts-min-height: initial}
</style>
```
Your result will then look like this (_I got this working on your site itself_):
![image](https://cloud.githubusercontent.com/assets/5303018/15231459/5246d6cc-1869-11e6-9c84-5a03bf41f1b6.png)

**Comment by kmulvey** [comment]
100%, thanks

**Comment by avdaredevil** [comment]
No Probs, leave a star if you liked the library @kmulvey
